services:
  apache:
    image: httpd:2.4
    container_name: apache
    ports:
      - "81:80"
    volumes:
      - ./app:/usr/local/apache2/htdocs
      - ./fpm/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./fpm/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    depends_on:
      - php-fpm
      - mysql
    networks:
      - phpnet

  php-fpm:
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql && php-fpm"
    depends_on:
      - mysql
    networks:
      - phpnet

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - phpnet

volumes:
  dbdata:

networks:
  phpnet:
